import { Event } from "@/lib/types";

export const israelGaza: Event = {
  slug: "israel-gaza",
  title: "Israel & Gaza",
  aliases: ["israel", "gaza", "palestine", "hamas", "middle east", "conflict"],
  category: "War & Conflict",
  date: "2023–2024",
  standfirst: "Even naming what happened is contested. Watch the verbs.",
  summary: "“Strikes,” “retaliation,” “massacre” — the verbs carry the argument.",
  sources: [
    {
      outlet: "The Times of Israel",
      country: "Israel",
      flag: "🇮🇱",
      orientation: "Private / commercial",
      accent: "#c0392b",
      headline: "Israel strikes Gaza in retaliation after deadly Hamas terror attack",
      contestedWords: ["retaliation", "terror attack"],
      framingWord: "retaliation",
      tone: "Defensive",
      focus: "Response to an initiating attack",
      url: "https://www.timesofisrael.com/israel-strikes-gaza-in-retaliation-after-deadly-hamas-terror-attack/",
      archiveUrl: "https://web.archive.org/web/20231009000000/https://www.timesofisrael.com/israel-strikes-gaza-in-retaliation-after-deadly-hamas-terror-attack/",
      publishDate: "9 Oct 2023",
      insight: "Calling the violence retaliation makes the present action feel downstream of an earlier crime, not a fresh decision that also deserves scrutiny.",
    },
    {
      outlet: "Al Jazeera",
      country: "Qatar",
      flag: "🇶🇦",
      orientation: "Pan-Arab",
      accent: "#2471a3",
      headline: "Israeli bombardment kills hundreds in Gaza as siege tightens",
      contestedWords: ["bombardment", "siege"],
      framingWord: "bombardment",
      tone: "Accusatory",
      focus: "Scale of civilian casualties and blockade",
      url: "https://www.aljazeera.com/news/2023/10/10/israeli-bombardment-kills-hundreds-in-gaza-as-siege-tightens",
      archiveUrl: "https://web.archive.org/web/20231011000000/https://www.aljazeera.com/news/2023/10/10/israeli-bombardment-kills-hundreds-in-gaza-as-siege-tightens",
      publishDate: "10 Oct 2023",
      insight: "This framing keeps attention on what is being done to Gaza and how civilians experience it, rather than on Israel's justification for acting.",
    },
    {
      outlet: "BBC",
      country: "United Kingdom",
      flag: "🇬🇧",
      orientation: "Public broadcaster",
      accent: "#7d3c98",
      headline: "Israel and Hamas at war as violence escalates across Gaza",
      contestedWords: ["at war", "violence escalates"],
      framingWord: "war",
      tone: "Measured",
      focus: "Two named parties; careful attribution",
      url: "https://www.bbc.com/news/world-middle-east-67036625",
      archiveUrl: "https://web.archive.org/web/20231009000000/https://www.bbc.com/news/world-middle-east-67036625",
      publishDate: "9 Oct 2023",
      insight: "BBC's phrasing names both parties and stresses escalation, which sounds more balanced but can also soften asymmetries in power and harm.",
    },
    {
      outlet: "Associated Press",
      country: "United States",
      flag: "🇺🇸",
      orientation: "Centrist",
      accent: "#b9770e",
      headline: "Conflict between Israel and Hamas deepens humanitarian crisis in Gaza",
      contestedWords: ["Conflict", "humanitarian crisis"],
      framingWord: "conflict",
      tone: "Neutral",
      focus: "Humanitarian consequences, minimal blame",
      url: "https://apnews.com/article/israel-hamas-war-gaza-humanitarian-crisis-6f1f7f1dfc6a2fda8c4f5c4fba0f0d2f",
      archiveUrl: "https://web.archive.org/web/20240101000000/https://apnews.com/article/israel-hamas-war-gaza-humanitarian-crisis-6f1f7f1dfc6a2fda8c4f5c4fba0f0d2f",
      publishDate: "2 Jan 2024",
      insight: "The humanitarian lens moves readers toward consequences first, but the generic noun 'conflict' can blur who is acting on whom.",
    },
  ],
  contestedTerms: [
    {
      term: "retaliation",
      accent: "#c0392b",
      why: "“Retaliation” presupposes an initiating act, placing responsibility on the other side and framing the response as justified.",
    },
    {
      term: "bombardment",
      accent: "#2471a3",
      why: "A one-directional word centres the force applied and its victims, foregrounding scale and civilian harm.",
    },
    {
      term: "war",
      accent: "#7d3c98",
      why: "Naming two combatants and attributing claims to each is a hallmark of outlets prioritising balance over a verdict.",
    },
    {
      term: "conflict",
      accent: "#b9770e",
      why: "The most neutral noun avoids assigning a starting point or a wrongdoer, keeping the focus on consequences.",
    },
  ],
  historicalContext:
    "The Israeli–Palestinian conflict spans over a century of disputes over land, statehood and security. Terminology here is deeply contested; word choice is itself part of the political argument.",
  methodology:
    "The dossier pairs outlet headlines with preserved snapshots so readers can check the original wording. Framing labels compare whether each source centers retaliation, bombardment, war or humanitarian fallout; background facts rely on widely cited institutional reporting rather than any single belligerent's rhetoric.",
  backgroundFacts: [
    {
      text: "Gaza is a densely populated coastal territory where Hamas has exercised de facto authority since 2007.",
      sourceLabel: "Britannica",
      url: "https://www.britannica.com/place/Gaza-Strip",
    },
    {
      text: "The UN and aid agencies repeatedly warned of a humanitarian emergency in Gaza during the war.",
      sourceLabel: "UN News",
      url: "https://news.un.org/en/story/2023/10/1142687",
    },
    {
      text: "Casualty figures were reported by Israeli authorities, Gaza health officials and international monitors, often with different methods and lag times.",
      sourceLabel: "OCHA",
      url: "https://www.ochaopt.org/",
    },
  ],
  timeline: [
    { date: "7 Oct 2023", label: "Hamas-led attack on southern Israel" },
    { date: "Oct 2023", label: "Israel launches large-scale operation in Gaza" },
    { date: "2024", label: "Humanitarian crisis and ceasefire negotiations" },
  ],
  missingPerspectives:
    "Headlines rarely centre civilians on both sides who want no part in the fighting, or the historical roots that each framing takes for granted.",
  reflectionQuestions: [
    "Notice the verbs: “strikes,” “bombardment,” “at war.” Which assigns blame, and which avoids it?",
    "Can any single headline describe this event without taking a side?",
    "What would you still need to know before forming your own view?",
  ],
};
