import { Event } from "@/lib/types";

export const russiaUkraine2022: Event = {
  slug: "russia-ukraine-2022",
  title: "Russia & Ukraine",
  aliases: ["ukraine", "russia", "putin", "war", "invasion", "special military operation"],
  category: "War & Conflict",
  date: "February 2022",
  standfirst: "The words the world used were not the same. Here is why.",
  summary: "One act, four names — from “invasion” to “special operation.”",
  sources: [
    {
      outlet: "BBC",
      country: "United Kingdom",
      flag: "🇬🇧",
      orientation: "Public broadcaster",
      accent: "#c0392b",
      headline: "Ukraine conflict: Russian forces attack from three sides",
      contestedWords: ["conflict", "attack"],
      framingWord: "conflict",
      tone: "Alarmed",
      focus: "Scale of aggression and threat to European order",
      url: "https://www.bbc.com/news/world-europe-60503037",
      archiveUrl: "https://web.archive.org/web/20220224034846/https://www.bbc.com/news/world-europe-60503037",
      publishDate: "24 Feb 2022",
      insight: "Even when the violence is unmistakable, 'conflict' sounds broader and less one-sided than explicitly naming an invasion.",
    },
    {
      outlet: "TASS",
      country: "Russia",
      flag: "🇷🇺",
      orientation: "State-owned",
      accent: "#2471a3",
      headline: "Donetsk and Lugansk leaders ask Putin to recognize republics' independence",
      contestedWords: ["recognize", "independence"],
      framingWord: "independence",
      tone: "Justifying",
      focus: "Defensive, limited action framed as protection",
      url: "https://tass.com/world/1407325",
      archiveUrl: "https://web.archive.org/web/20220221180000/https://tass.com/world/1407325",
      publishDate: "21 Feb 2022",
      insight: "This framing moves the story toward recognition and self-determination, away from what Russian troops were about to do next.",
    },
    {
      outlet: "Reuters",
      country: "United Kingdom",
      flag: "🇬🇧",
      orientation: "Centrist",
      accent: "#7d3c98",
      headline: "Russia attacks Ukraine as defiant Putin warns US, NATO",
      contestedWords: ["attacks", "warns"],
      framingWord: "attack",
      tone: "Detached",
      focus: "Neutral nouns; emphasis on calls for calm",
      url: "https://www.reuters.com/world/europe/russia-attacks-ukraine-defiant-putin-warns-us-nato-2022-02-24/",
      archiveUrl: "https://web.archive.org/web/20220224055000/https://www.reuters.com/world/europe/russia-attacks-ukraine-defiant-putin-warns-us-nato-2022-02-24/",
      publishDate: "24 Feb 2022",
      insight: "Reuters names the attack directly, but the headline still centers state actors and strategic warning more than civilians on the ground.",
    },
    {
      outlet: "Al Jazeera",
      country: "Qatar",
      flag: "🇶🇦",
      orientation: "Pan-Arab",
      accent: "#b9770e",
      headline: "Russia strikes Ukraine army base near Poland as it widens attacks",
      contestedWords: ["strikes", "widens attacks"],
      framingWord: "strikes",
      tone: "Humanitarian",
      focus: "Impact on ordinary people on the ground",
      url: "https://www.aljazeera.com/news/2022/3/13/russia-air-strikes-hit-ukraine-military-base-near-poland",
      archiveUrl: "https://web.archive.org/web/20220314030000/https://www.aljazeera.com/news/2022/3/13/russia-air-strikes-hit-ukraine-military-base-near-poland",
      publishDate: "14 Mar 2022",
      insight: "The emphasis stays on force applied to Ukraine and on the widening fallout, which keeps human consequences in the foreground.",
    },
  ],
  contestedTerms: [
    {
      term: "conflict",
      accent: "#c0392b",
      why: "“Conflict” acknowledges violence but leaves more room for ambiguity than a headline that names an invader outright.",
    },
    {
      term: "independence",
      accent: "#2471a3",
      why: "This lens turns the story toward recognition and sovereignty claims, which can make military escalation feel like a consequence rather than the core act.",
    },
    {
      term: "attack",
      accent: "#7d3c98",
      why: "“Attack” is clearer than a neutral noun, but it still keeps the focus at the level of states, strategy and warnings.",
    },
    {
      term: "strikes",
      accent: "#b9770e",
      why: "“Strikes” foregrounds the force being used and the places it lands, nudging readers toward consequences on the ground.",
    },
  ],
  historicalContext:
    "Russia and Ukraine share deep historical ties dating to Kievan Rus'. After the 2014 annexation of Crimea and war in the Donbass, language about the region was already politically charged long before February 2022.",
  methodology:
    "Headlines are linked to archived or archival-style snapshots so readers can inspect the original wording themselves. Framing terms were picked by comparing how outlets described related milestones in the same war; background facts come from institutions documenting the conflict rather than from the headlines alone.",
  backgroundFacts: [
    {
      text: "On 24 February 2022, Russian armed forces crossed into Ukrainian territory.",
      sourceLabel: "UN News",
      url: "https://news.un.org/en/story/2022/02/1112952",
    },
    {
      text: "On 2 March 2022, the UN General Assembly voted 141-5 to demand Russia's withdrawal.",
      sourceLabel: "UN Press",
      url: "https://press.un.org/en/2022/ga12407.doc.htm",
    },
    {
      text: "Millions of Ukrainians were displaced within weeks of the invasion.",
      sourceLabel: "UNHCR",
      url: "https://www.unhcr.org/emergencies/ukraine-emergency",
    },
  ],
  timeline: [
    { date: "2014", label: "Russia annexes Crimea; war begins in Donbass" },
    { date: "24 Feb 2022", label: "Russian forces cross into Ukraine" },
    { date: "2 Mar 2022", label: "UN General Assembly demands withdrawal (141–5)" },
  ],
  missingPerspectives:
    "Across all four headlines, the voices least heard are ordinary Russians and Ukrainians who disagree with their governments, and the long-term diplomatic history that shaped both sides' positions.",
  reflectionQuestions: [
    "Which single word changed how you felt the fastest?",
    "If you only read one of these outlets for a year, what would you never learn?",
    "Is a “neutral” word like “crisis” always the most honest one — or can it hide something?",
  ],
};
